name: Sean King
title: Sean King
author: Sean King
email: r.sean.king@gmail.com
twitter_username: rseanking
github_username: seanking
social:
  name: Sean King
  links:
    - https://twitter.com/rseanking
    - https://www.linkedin.com/in/rseanking
    - https://github.com/seanking

permalink: pretty
permalink: /blog/:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag

google_tag_manager: UA-113421066-1
  
exclude: ["Gemfile", "Gemfile.lock", "node_modules", "package.json", "package-lock.json"]

theme: jekyll-theme-cayman